### ISSUE TITLE
Github major issue (priority)

### ISSUE THREAD

**Issue by chrisjay629** [wdi-atx-10/class#8]
I have somehow put Desktop on my local copy of master. atm I can't use my computer w/github until this is fixed. Kollin has probably fixed this issue before. Please help.

**Comment by dirkdunn** [comment]
Hi Chris, did you find a solution for this?

**Check out this page for an answer on how to rollback to a previous git commit**
http://stackoverflow.com/questions/4372435/how-can-i-rollback-a-github-repository-to-a-specific-commit

**Also, in order to be able to find the commit that you want to revert back to, run this command**
`
git log
`

**Comment by dirkdunn** [comment]
The commit ID will be the long sequence of characters that will look something like this one you run git log:

aaae510d6d5973021e95ba2ed4326e8cd81cee2c
